### ISSUE TITLE
Deprecation of the User streams API

### ISSUE THREAD

**Issue by tesaguri** [tesaguri/twitter-stream-rs#17]
Twitter is going to abandon its [User streams] (and Site stream) API on ~June 19, 2018~, and `TwitterStreamBuilder::user` and `TwitterStream::user` methods will no longer work. So I will remove these methods after then.

[User Streams]: https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/user-stream

The [POST statuses/filter] and [GET statuses/sample] APIs will (I think) still work, so the library will continue to be maintained.

[POST statuses/filter]: https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter
[GET statuses/sample]: https://developer.twitter.com/en/docs/tweets/sample-realtime/api-reference/get-statuses-sample

**Comment by dmizuk** [comment]
The deprecation date has been postponed to 2018-8-16:
https://twitter.com/TwitterDev/status/996782994181558273

**Comment by tesaguri** [comment]
Twitter announced a detailed schedule for the deprecation:
https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746

Accordingly, I will update the library after 2018-8-23 16:00:00 UTC, removing `{TwitterStreamBuilder,TwitterStream}::user` methods.

**Comment by tesaguri** [comment]
User Streams have been completely turned off so I have published version 0.7.0 to crates.io, which removed User Streams support.
